### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by rorroap** [wpgp/wpgpDataQPD#10]
When I try to download a map this message appears:

![Captura de pantalla 2024-09-06 221111](https://github.com/user-attachments/assets/cf8fb1d9-c853-49ac-b71e-67522fbd0ef5)

![Captura de pantalla 2024-09-06 221120](https://github.com/user-attachments/assets/a55bb137-2137-44f7-864f-268e4c7861b5)

What should I do?

**Comment by arongergely** [comment]
Thank you @rorroap , this  looks like a bug in the progress bar. I am adding a fix

**Comment by arongergely** [comment]
@bondarenkom could you make a new release to the QGIS plugin repository? I added a tag for v1.2.1.

**Comment by arongergely** [comment]
@rorroap after @bondarenkom made the release you should update/reinstall the plugin. Downloads should work fine afterwards.

**Comment by arongergely** [comment]
@rorroap for now I made a release here on github:
https://github.com/wpgp/wpgpDataQPD/releases/tag/v1.2.1

You can download the plugin .zip file and install it locally in QGIS. See https://docs.qgis.org/testing/en/docs/training_manual/qgis_plugins/fetching_plugins.html
