### ISSUE TITLE
This plugin is broken Missing metadata file 

### ISSUE THREAD

**Issue by rejusam** [wpgp/wpgpDataQPD#9]
I am getting the following error:
![Screenshot 2021-05-26 at 11 39 39 AM](https://user-images.githubusercontent.com/6176357/119581668-1ae9fe80-be17-11eb-9a0f-42e6e396f3d7.png)

**Comment by arongergely** [comment]
Hi @rejusam thanks for submitting an issue. It seems you are looking at the the wrong item (the 1st row of the list) in the plugin window. I see wgpgDatasets is the last. 

Could you check again that indeed wpgpDatasets is broken?

**Comment by rejusam** [comment]
Thanks.. wpgpDatasets is not broken. And it is woking now.
